# fly.toml app configuration file generated for gds-final-project on 2025-05-07T15:26:45-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gds-final-project'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
